# Generated by Django 5.0.6 on 2024-07-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_about_user_avatar_user_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
